version: "2"
run:
  tests: true
  timeout: 5m
  issues-exit-code: 1
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
#    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
#    - gocritic
    - gocyclo
    - goheader
    - goprintffuncname
    - gosec
    - gosmopolitan
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnesserr
#    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - revive
#    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - whitespace
    - zerologlint
    - govet
    - ineffassign
    - unused
  settings:
    cyclop:
      max-complexity: 15
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          deny:
            - pkg: reflect
              desc: Reflection is never clear.
            - pkg: gob
              desc: Please convert types manually
    dupl:
      threshold: 100
#     errcheck:
#       check-type-assertions: true
#       check-blank: true
#       exclude-functions:
#         - fmt:.*
#         - io/ioutil:^Read.*
    goconst:
      min-len: 3
      min-occurrences: 5
#     gocritic:
#       enabled-tags:
#         - diagnostic
#         - experimental
#         - opinionated
#         - performance
#         - style
#       settings:
#         captLocal:
#           paramsOnly: true
#         rangeValCopy:
#           sizeThreshold: 32
    lll:
      tab-width: 1
    nolintlint:
      require-explanation: true
      require-specific: true
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    unparam:
      check-exported: false
    goheader:
      template: |-
        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    misspell:
      locale: US
    revive:
      rules:
        - name: dot-imports
          disabled: true
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goheader
        path: zz_(.+)\.go
      - path: (.+)\.go$
        text: declaration of "(err|ctx)" shadows declaration at
    paths:
      - hack
      - charts
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: true
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(github.com/linode/karpenter-provider-linode)
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/linode/karpenter-provider-linode
  exclusions:
    generated: lax
    paths:
      - zz_(.+)\.go
      - hack
      - charts
      - third_party$
      - builtin$
      - examples$
