namespace: kube-system

firewall:
  inbound:
    - label: allow-karpl-webhook
      action: ACCEPT
      description: Allow KARPL admission webhook traffic
      protocol: TCP
      ports: "8443"
      addresses:
        ipv4:
          - 192.168.128.0/17
