apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: consolidation-step-scale
  labels:
    e2e.linode.dev/cleanup: "true"
spec:
  template:
    metadata:
      labels:
        e2e.linode.dev/consolidation-step-scale: "true"
        e2e.linode.dev/cleanup: "true"
    spec:
      requirements:
        - key: e2e.linode.dev/consolidation-step-scale
          operator: Exists
        - key: karpenter.k8s.linode/instance-memory
          operator: Lt
          values: ["8193"]
      taints:
        - key: e2e.linode.dev/test
          value: "true"
          effect: NoSchedule
      nodeClassRef:
        group: karpenter.k8s.linode
        kind: LinodeNodeClass
        name: default
  limits:
    cpu: 1000
