apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-no-toleration
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate-no-toleration
  template:
    metadata:
      labels:
        app: inflate-no-toleration
    spec:
      terminationGracePeriodSeconds: 0
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      nodeSelector:
        e2e.linode.dev/dedicated: tainted
      containers:
      - name: inflate
        image: mirror.registry.linodelke.net/k8s/pause:3.9
        resources:
          requests:
            cpu: 1
        securityContext:
          allowPrivilegeEscalation: false
