apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: tainted
  labels:
    e2e.linode.dev/cleanup: "true"
spec:
  template:
    metadata:
      labels:
        e2e.linode.dev/dedicated: tainted
        e2e.linode.dev/cleanup: "true"
    spec:
      requirements:
        - key: e2e.linode.dev/dedicated
          operator: Exists
      taints:
        - key: e2e.linode.dev/test
          value: "true"
          effect: NoSchedule
        - key: e2e.linode.dev/dedicated
          value: tainted
          effect: NoSchedule
      nodeClassRef:
        group: karpenter.k8s.linode
        kind: LinodeNodeClass
        name: default
  limits:
    cpu: 1000
