name: e2e-nightly-trigger

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  pull-requests: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  E2E_STANDARD_ALLOWED_ENDPOINTS: >-
    *.us-sea-2-gw.linodelke.net:443
    api.github.com:443
    api.linode.com:443
    api.segment.io:443
    artifacts.nixos.org:443
    auth.docker.io:443
    cache.nixos.org:443
    files.pythonhosted.org:443
    gcr.io:443
    github.com:443
    index.docker.io:443
    ipv4.icanhazip.com:443
    linode.github.io:443
    pypi.org:443
    registry-1.docker.io:443
    release-assets.githubusercontent.com:443
    releases.jetify.com:443
    releases.jetpack.io:443
  E2E_ENTERPRISE_ALLOWED_ENDPOINTS: >-
    *.api.us-sea.enterprise.linodelke.net:6443
    api.github.com:443
    api.linode.com:443
    api.segment.io:443
    artifacts.nixos.org:443
    auth.docker.io:443
    cache.nixos.org:443
    cloud.tilt.dev:443
    files.pythonhosted.org:443
    gcr.io:443
    github.com:443
    index.docker.io:443
    ipv4.icanhazip.com:443
    linode.github.io:443
    pypi.org:443
    registry-1.docker.io:443
    release-assets.githubusercontent.com:443
    releases.jetify.com:443
    releases.jetpack.io:443

jobs:
  e2e-nightly-standard:
    name: Nightly E2E (standard)
    uses: ./.github/workflows/e2e.yaml
    with:
      cluster_name: ${{ format('kns-{0}', github.run_id) }}
      cluster_tier: standard
      chainsaw_selector: all
      cleanup: true
      timeout_minutes: 90
      cleanup_timeout_minutes: 20
      harden_runner_egress_policy: block
      harden_runner_allowed_endpoints: ${{ env.E2E_STANDARD_ALLOWED_ENDPOINTS }}
    secrets: inherit

  e2e-nightly-enterprise:
    name: Nightly E2E (enterprise)
    uses: ./.github/workflows/e2e.yaml
    with:
      cluster_name: ${{ format('kne-{0}', github.run_id) }}
      cluster_tier: enterprise
      chainsaw_selector: all
      cleanup: true
      timeout_minutes: 90
      cleanup_timeout_minutes: 20
      harden_runner_egress_policy: block
      harden_runner_allowed_endpoints: ${{ env.E2E_ENTERPRISE_ALLOWED_ENDPOINTS }}
    secrets: inherit
