name: e2e-pr-cleanup-trigger

on:
  pull_request: # TODO: change this to pull_request_target so people don't need to set their own LINODE_TOKEN secret in their forks
    types: [closed]
    branches:
      - '**'

permissions:
  contents: read
  pull-requests: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cleanup-pr-close:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
      LINODE_CLI_TOKEN: ${{ secrets.LINODE_TOKEN }}
      CLUSTER_NAME: ${{ format('kpr-{0}', github.event.pull_request.number) }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.linode.com:443
            api.segment.io:443
            artifacts.nixos.org:443
            cache.nixos.org:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
            release-assets.githubusercontent.com:443
            releases.jetify.com:443
            releases.jetpack.io:443
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: E2E Cleanup on PR Close
        uses: ./.github/actions/e2e
        with:
          cleanup_cluster: "true"
