name: e2e-main-trigger

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          disable-sudo: true
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: .github/filters.yml

  e2e-main-standard:
    name: Main E2E (standard)
    needs: [changes]
    if: ${{ contains(fromJSON(needs.changes.outputs.paths), 'src') || contains(fromJSON(needs.changes.outputs.paths), 'e2e_ci') }}
    uses: ./.github/workflows/e2e.yaml
    with:
      cluster_name: ${{ format('kps-{0}', github.run_id) }}
      cluster_tier: standard
      chainsaw_selector: pr
      cleanup: true
      timeout_minutes: 60
      cleanup_timeout_minutes: 20
    secrets: inherit

  e2e-main-enterprise:
    name: Main E2E (enterprise)
    needs: [changes]
    if: ${{ contains(fromJSON(needs.changes.outputs.paths), 'src') || contains(fromJSON(needs.changes.outputs.paths), 'e2e_ci') }}
    uses: ./.github/workflows/e2e.yaml
    with:
      cluster_name: ${{ format('kpe-{0}', github.run_id) }}
      cluster_tier: enterprise
      chainsaw_selector: pr
      cleanup: true
      timeout_minutes: 90
      cleanup_timeout_minutes: 20
    secrets: inherit
