name: e2e

on:
  workflow_call:
    inputs:
      cluster_name:
        type: string
        required: true
      chainsaw_selector:
        type: string
        required: true
      cleanup:
        type: boolean
        required: true
      timeout_minutes:
        type: number
        required: false
        default: 60
      cleanup_timeout_minutes:
        type: number
        required: false
        default: 20
      chainsaw_flags:
        type: string
        required: false
        default: --config .chainsaw.yaml

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}
    env:
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
      LINODE_CLI_TOKEN: ${{ secrets.LINODE_TOKEN }}
      LINODE_REGION: us-sea
      CLUSTER_NAME: ${{ inputs.cluster_name }}
      CHAINSAW_SELECTOR: ${{ inputs.chainsaw_selector }}
      CHAINSAW_FLAGS: ${{ inputs.chainsaw_flags }}

    steps:
      - name: E2E setup and test
        uses: ./.github/actions/e2e
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          devbox_command: setup-and-test-e2e

  cleanup:
    if: ${{ inputs.cleanup && always() }}
    needs: [e2e]
    timeout-minutes: ${{ inputs.cleanup_timeout_minutes }}
    runs-on: ubuntu-latest
    env:
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
      LINODE_CLI_TOKEN: ${{ secrets.LINODE_TOKEN }}
      CLUSTER_NAME: ${{ inputs.cluster_name }}

    steps:
      - name: E2E Cleanup 
        uses: ./.github/actions/e2e
        with:
          cleanup_cluster: "true"
