name: e2e

on:
  workflow_call:
    inputs:
      cluster_name:
        type: string
        required: true
      cluster_tier:
        type: string
        required: false
        default: standard
      chainsaw_selector:
        type: string
        required: true
      cleanup:
        type: boolean
        required: true
      timeout_minutes:
        type: number
        required: false
        default: 60
      cleanup_timeout_minutes:
        type: number
        required: false
        default: 20
      chainsaw_flags:
        type: string
        required: false
        default: --config .chainsaw.yaml
      harden_runner_egress_policy:
        type: string
        required: false
        default: audit
      harden_runner_allowed_endpoints:
        type: string
        required: false
        default: ""

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  e2e:
    name: E2E (${{ inputs.cluster_tier }})
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}
    env:
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
      LINODE_CLI_TOKEN: ${{ secrets.LINODE_TOKEN }}
      LINODE_REGION: us-sea
      CLUSTER_NAME: ${{ inputs.cluster_name }}
      CLUSTER_TIER: ${{ inputs.cluster_tier }}
      CHAINSAW_SELECTOR: ${{ inputs.chainsaw_selector }}
      CHAINSAW_FLAGS: ${{ inputs.chainsaw_flags }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: ${{ inputs.harden_runner_egress_policy }}
          allowed-endpoints: ${{ inputs.harden_runner_allowed_endpoints }}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: E2E setup and test
        uses: ./.github/actions/e2e
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          devbox_command: setup-and-test-e2e

  cleanup:
    name: Cleanup (${{ inputs.cluster_tier }})
    if: ${{ inputs.cleanup && always() }}
    needs: [e2e]
    timeout-minutes: ${{ inputs.cleanup_timeout_minutes }}
    runs-on: ubuntu-latest
    env:
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
      LINODE_CLI_TOKEN: ${{ secrets.LINODE_TOKEN }}
      CLUSTER_NAME: ${{ inputs.cluster_name }}
      CLUSTER_TIER: ${{ inputs.cluster_tier }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: E2E Cleanup 
        uses: ./.github/actions/e2e
        with:
          cleanup_cluster: "true"
