name: Image
on:
  push:
    branches:
      - "main"
    tags:
      - "*"

permissions:
  contents: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
          allowed-endpoints: >
            api.github.com:443
            api.segment.io:443
            artifacts.nixos.org:443
            auth.docker.io:443
            cache.nixos.org:443
            gcr.io:443
            github.com:443
            proxy.golang.org:443
            registry-1.docker.io:443
            release-assets.githubusercontent.com:443
            releases.jetify.com:443
            releases.jetpack.io:443
            storage.googleapis.com:443
            sum.golang.org:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0

      - name: Build and push image
        run: devbox run build-karpl-image
