name: Image
on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
          allowed-endpoints: >
            api.github.com:443
            api.segment.io:443
            artifacts.nixos.org:443
            auth.docker.io:443
            identity.docker.com:443
            cache.nixos.org:443
            gcr.io:443
            github.com:443
            index.docker.io:443
            get.jetify.com:443
            get.jetpack.io:443
            proxy.golang.org:443
            registry-1.docker.io:443
            release-assets.githubusercontent.com:443
            releases.jetify.com:443
            releases.jetpack.io:443
            storage.googleapis.com:443
            sum.golang.org:443

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        env:
          DOCKERHUB_OIDC_CONNECTIONID: ${{ secrets.DOCKERHUB_OIDC_CONNECTIONID }}
        with:
          username: ${{ github.repository_owner }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0

      - name: Build and push image
        run: devbox run build-karpl-image
